services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - 3000:80

  api:
    build: ./api
    environment:
      DATABASE_URL: ""
      PORT: 5000
    entrypoint: /app/kms-api
    restart: unless-stopped