services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - 3000:80

  api:
    build: ./api
    networks:
        - backend
    environment:
        DATABASE_URL: ""
        PORT: 5000
    ports:
      - 5000:5000
    entrypoint: /app/kms-api
    restart: unless-stopped

networks:
  backend:
    external: true
