// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package kmsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ptik struct {
	Nim          int32
	Nama         string
	TempatLahir  string
	TanggalLahir pgtype.Date
}

type Submission struct {
	ID      int32
	UserNim pgtype.Int4
	Img     pgtype.Text
}

type SubmissionScore struct {
	ID           int32
	UserNim      pgtype.Int4
	SubmissionID pgtype.Int4
}

type User struct {
	ID  int32
	Nim pgtype.Int4
	Pfp pgtype.Text
}
