// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package kmsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addScore = `-- name: AddScore :exec

INSERT INTO submission_score (user_nim, submission_id) VALUES ($1, $2) 
ON CONFLICT (user_nim) DO UPDATE SET submission_id=$2
`

type AddScoreParams struct {
	UserNim      pgtype.Int4
	SubmissionID pgtype.Int4
}

func (q *Queries) AddScore(ctx context.Context, arg AddScoreParams) error {
	_, err := q.db.Exec(ctx, addScore, arg.UserNim, arg.SubmissionID)
	return err
}

const addSubmission = `-- name: AddSubmission :exec
INSERT INTO submission (user_nim, img) VALUES ($1, $2) ON CONFLICT (img) DO NOTHING
`

type AddSubmissionParams struct {
	UserNim pgtype.Int4
	Img     pgtype.Text
}

func (q *Queries) AddSubmission(ctx context.Context, arg AddSubmissionParams) error {
	_, err := q.db.Exec(ctx, addSubmission, arg.UserNim, arg.Img)
	return err
}

const checkSubmission = `-- name: CheckSubmission :exec
SELECT EXISTS(SELECT 1 FROM submission WHERE img = $1)
`

func (q *Queries) CheckSubmission(ctx context.Context, img pgtype.Text) error {
	_, err := q.db.Exec(ctx, checkSubmission, img)
	return err
}

const checkUser = `-- name: CheckUser :one
SELECT u.id, u.nim FROM users u JOIN ptik p using (nim) where u.nim=$1 and p.tanggal_lahir=$2 LIMIT 1
`

type CheckUserParams struct {
	Nim          pgtype.Int4
	TanggalLahir pgtype.Date
}

type CheckUserRow struct {
	ID  int32
	Nim pgtype.Int4
}

func (q *Queries) CheckUser(ctx context.Context, arg CheckUserParams) (CheckUserRow, error) {
	row := q.db.QueryRow(ctx, checkUser, arg.Nim, arg.TanggalLahir)
	var i CheckUserRow
	err := row.Scan(&i.ID, &i.Nim)
	return i, err
}

const getSubmission = `-- name: GetSubmission :many
SELECT s.id, img, COALESCE((SELECT COUNT(user_nim) FROM submission_score WHERE submission_id=s.id 
GROUP BY submission_id), 0) as votes, p.nama, COALESCE(pfp, '') as user_pfp, 
(SELECT EXISTS(SELECT 1 FROM submission_score WHERE submission_id=s.id AND s.user_nim=$1)) FROM submission s
JOIN users u ON s.user_nim=u.nim
JOIN ptik p ON p.nim=u.nim
`

type GetSubmissionRow struct {
	ID      int32
	Img     pgtype.Text
	Votes   interface{}
	Nama    string
	UserPfp string
	Exists  bool
}

func (q *Queries) GetSubmission(ctx context.Context, userNim pgtype.Int4) ([]GetSubmissionRow, error) {
	rows, err := q.db.Query(ctx, getSubmission, userNim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmissionRow
	for rows.Next() {
		var i GetSubmissionRow
		if err := rows.Scan(
			&i.ID,
			&i.Img,
			&i.Votes,
			&i.Nama,
			&i.UserPfp,
			&i.Exists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT CONCAT('K35240', LPAD(p.nim::text, 2, '0')) as nim, p.nama, p.tempat_lahir, TO_CHAR(p.tanggal_lahir, 'YYYY-MM-DD') as tanggal_lahir, COALESCE(pfp, '') FROM users u JOIN ptik p using (nim) WHERE u.nim = $1 LIMIT 1
`

type GetUserRow struct {
	Nim          interface{}
	Nama         string
	TempatLahir  string
	TanggalLahir string
	Pfp          string
}

func (q *Queries) GetUser(ctx context.Context, nim pgtype.Int4) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, nim)
	var i GetUserRow
	err := row.Scan(
		&i.Nim,
		&i.Nama,
		&i.TempatLahir,
		&i.TanggalLahir,
		&i.Pfp,
	)
	return i, err
}

const listMahasiswa = `-- name: ListMahasiswa :many
SELECT CONCAT('K35240', LPAD(nim::text, 2, '0')) as nim, nama, tempat_lahir, TO_CHAR(tanggal_lahir, 'YYYY-MM-DD') as tanggal_lahir FROM ptik
`

type ListMahasiswaRow struct {
	Nim          interface{}
	Nama         string
	TempatLahir  string
	TanggalLahir string
}

func (q *Queries) ListMahasiswa(ctx context.Context) ([]ListMahasiswaRow, error) {
	rows, err := q.db.Query(ctx, listMahasiswa)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMahasiswaRow
	for rows.Next() {
		var i ListMahasiswaRow
		if err := rows.Scan(
			&i.Nim,
			&i.Nama,
			&i.TempatLahir,
			&i.TanggalLahir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfilePicture = `-- name: UpdateProfilePicture :exec
UPDATE users SET pfp=$1 where nim=$2
`

type UpdateProfilePictureParams struct {
	Pfp pgtype.Text
	Nim pgtype.Int4
}

func (q *Queries) UpdateProfilePicture(ctx context.Context, arg UpdateProfilePictureParams) error {
	_, err := q.db.Exec(ctx, updateProfilePicture, arg.Pfp, arg.Nim)
	return err
}
