// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ptik struct {
	ID           int32
	Nim          string
	Nama         string
	TempatLahir  string
	TanggalLahir pgtype.Date
	Angkatan     pgtype.Int4
}

type Submission struct {
	ID     int32
	UserID pgtype.Int4
	Img    pgtype.Text
}

type SubmissionScore struct {
	ID           int32
	UserID       pgtype.Int4
	SubmissionID pgtype.Int4
}

type User struct {
	ID       int32
	Password pgtype.Text
	Pfp      pgtype.Text
}
