// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ptik struct {
	Nim          int32
	Nama         string
	TempatLahir  string
	TanggalLahir pgtype.Date
	Angkatan     pgtype.Int4
}

type User struct {
	Nim      int32
	Password pgtype.Text
	Pfp      pgtype.Text
}
