// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ptik struct {
	ID           int32
	Nim          string
	Nama         string
	TempatLahir  string
	TanggalLahir pgtype.Date
	Angkatan     pgtype.Int4
}

type Tuga struct {
	ID        int32
	Nama      string
	Matkul    string
	Deskripsi string
	Deadline  pgtype.Date
	Link      pgtype.Text
}

type User struct {
	ID       int32
	Password pgtype.Text
	Pfp      pgtype.Text
}
