// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getLink = `-- name: GetLink :many
SELECT nim, nama, tempat_lahir, tanggal_lahir, angkatan FROM ptik
`

func (q *Queries) GetLink(ctx context.Context) ([]Ptik, error) {
	rows, err := q.db.Query(ctx, getLink)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ptik
	for rows.Next() {
		var i Ptik
		if err := rows.Scan(
			&i.Nim,
			&i.Nama,
			&i.TempatLahir,
			&i.TanggalLahir,
			&i.Angkatan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
