// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUser = `-- name: CheckUser :one
select users.id, password from users join ptik using (id) where nim = $1
`

type CheckUserRow struct {
	ID       int32
	Password pgtype.Text
}

func (q *Queries) CheckUser(ctx context.Context, nim string) (CheckUserRow, error) {
	row := q.db.QueryRow(ctx, checkUser, nim)
	var i CheckUserRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const getPtik = `-- name: GetPtik :many
select id, nim, nama, tempat_lahir, tanggal_lahir, angkatan from ptik
`

func (q *Queries) GetPtik(ctx context.Context) ([]Ptik, error) {
	rows, err := q.db.Query(ctx, getPtik)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ptik
	for rows.Next() {
		var i Ptik
		if err := rows.Scan(
			&i.ID,
			&i.Nim,
			&i.Nama,
			&i.TempatLahir,
			&i.TanggalLahir,
			&i.Angkatan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
select users.id, pfp, nim, nama, tempat_lahir, tanggal_lahir, angkatan from users join ptik using (id) where users.id = $1 LIMIT 1
`

type GetUserRow struct {
	ID           int32
	Pfp          pgtype.Text
	Nim          string
	Nama         string
	TempatLahir  string
	TanggalLahir pgtype.Date
	Angkatan     pgtype.Int4
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Pfp,
		&i.Nim,
		&i.Nama,
		&i.TempatLahir,
		&i.TanggalLahir,
		&i.Angkatan,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
update users set password = $1 from ptik where users.id = ptik.id and nim = $2 and tanggal_lahir = $3
`

type UpdatePasswordParams struct {
	Password     pgtype.Text
	Nim          string
	TanggalLahir pgtype.Date
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Password, arg.Nim, arg.TanggalLahir)
	return err
}
